# Generated by Django 4.2.7 on 2023-11-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
